server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: vhukhudo
    password: "vhukhudomateka"      # <-- updated to match new Postgres password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: myjwtsecretmyjwtsecretmyjwtsecret
  expiration: 3600000
